import clsx from "clsx";
import Script from "next/script";
import { Poppins } from "next/font/google";
import { AOSInit } from "~/utils/aos";

import "~/styles/generalStyles.css";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script
        src="https://kit.fontawesome.com/0904eaacfa.js"
        crossOrigin="anonymous"
      ></Script>
      <AOSInit />
      <body
        className={clsx("bg-dark-white", poppins.className)}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
