import { Poppins } from "next/font/google";
import { AOSInit } from "~/utils/aos";
import { config } from "@fortawesome/fontawesome-svg-core";

import "~/styles/generalStyles.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={poppins.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
